import { PageFlip } from '@gullabs/flipbook-core';

/**
 * Canvas-mode e2e harness.
 *
 * Deliberately separate from `main.ts` and from `canvas-demo.ts`: this is not a
 * showcase, it is a rig for reading pixels off a canvas deterministically. The
 * fixtures are generated by `scripts/gen-canvas-fixtures.mjs`, so the exact
 * colour at every probe point is derivable from source rather than being a
 * committed mystery.
 *
 * `data-ready` says the engine was constructed and the load promise settled.
 * It does NOT always mean every image decoded — under ADR 0001 the promise
 * settles when the initial spread has settled (decoded or failed). Tests must
 * still poll pixels; never trust this flag alone.
 *
 * Query knobs (Phase 0 + Phase 2 ADR):
 *   ?pages=N              how many identity pages (default 6)
 *   ?fixture=transparent|tall|wide|square|stripe|broken|corrupt|blank
 *   ?fit=contain|cover|fill
 *   ?inset=0.028          fraction of page width (ADR Decision 4)
 *   ?portrait=1
 *   ?cover=1
 *   ?rtl=1
 *   ?shadow=1
 *   ?fractional=1
 *   ?reducedMotion=0|1
 *   ?flippingTime=N
 *   ?pageBackground=#hex
 *   ?imageBackground=#hex  per-page background override when descriptors work
 */

const root = document.getElementById('book');
if (!(root instanceof HTMLElement)) {
  throw new Error('#book root element is required');
}

const params = new URLSearchParams(window.location.search);
const flag = (name: string): boolean => params.get(name) === '1';

if (flag('fractional')) document.body.dataset['fractional'] = '1';
if (flag('hidden')) document.body.dataset['hidden'] = '1';

const pageCount = Number(params.get('pages') ?? 6);
const fixture = params.get('fixture') ?? 'pages';
const fit = params.get('fit'); // contain | cover | fill
const insetRaw = params.get('inset');
const inset = insetRaw !== null && insetRaw !== '' ? Number(insetRaw) : undefined;
const pageBackground = params.get('pageBackground') ?? '#f4ecd8';
const imageBackground = params.get('imageBackground') ?? undefined;

type Descriptor = {
  src?: string;
  alt: string;
  fit?: 'contain' | 'cover' | 'fill';
  inset?: number;
  background?: string;
  blank?: true;
};

/**
 * Build the page list the ADR wants. When the engine still only accepts
 * `string[]`, we fall back to bare URLs so Phase 0 stays green while Phase 2
 * lands — see `toLoadArg`.
 */
function buildSources(): Descriptor[] {
  switch (fixture) {
    case 'transparent':
      return [
        { src: '/fixtures/canvas/transparent.png', alt: 'Transparent border fixture' },
        { src: '/fixtures/canvas/page-1.png', alt: 'Page 1' },
      ];
    case 'tall':
      return [
        { src: '/fixtures/canvas/tall.png', alt: 'Tall quadrants 200x400' },
        { src: '/fixtures/canvas/page-1.png', alt: 'Page 1' },
      ];
    case 'wide':
      return [
        { src: '/fixtures/canvas/wide.png', alt: 'Wide quadrants 600x200' },
        { src: '/fixtures/canvas/page-1.png', alt: 'Page 1' },
      ];
    case 'square':
      return [
        { src: '/fixtures/canvas/square.png', alt: 'Square quadrants 300x300' },
        { src: '/fixtures/canvas/page-1.png', alt: 'Page 1' },
      ];
    case 'stripe':
      return [
        { src: '/fixtures/canvas/stripe.png', alt: 'Narrow tall stripe' },
        { src: '/fixtures/canvas/page-1.png', alt: 'Page 1' },
      ];
    case 'broken':
      // 404 — network failure path.
      return [
        { src: '/fixtures/canvas/does-not-exist-404.png', alt: 'Missing asset' },
        { src: '/fixtures/canvas/page-1.png', alt: 'Page 1' },
      ];
    case 'corrupt':
      // 200 with undecodable body — decode failure path.
      return [
        { src: '/fixtures/canvas/corrupt.png', alt: 'Corrupt PNG' },
        { src: '/fixtures/canvas/page-1.png', alt: 'Page 1' },
      ];
    case 'blank':
      // ADR scope: blank leaf is a first-class variant (no bitmap).
      return [
        { blank: true, alt: '' },
        { src: '/fixtures/canvas/page-1.png', alt: 'Page 1' },
      ];
    case 'mixed':
      // Landscape spread: blank pad + image, exercises both leaf kinds.
      return [
        { blank: true, alt: '' },
        { src: '/fixtures/canvas/page-0.png', alt: 'Page 0' },
        { src: '/fixtures/canvas/tall.png', alt: 'Tall' },
        { src: '/fixtures/canvas/page-1.png', alt: 'Page 1' },
      ];
    default:
      return Array.from({ length: pageCount }, (_, i) => ({
        src: `/fixtures/canvas/page-${String(i % 6)}.png`,
        alt: `Page ${i}`,
      }));
  }
}

const descriptors = buildSources().map((d) => {
  const out: Descriptor = { ...d };
  if (fit === 'contain' || fit === 'cover' || fit === 'fill') out.fit = fit;
  if (inset !== undefined && Number.isFinite(inset)) out.inset = inset;
  if (imageBackground !== undefined) out.background = imageBackground;
  return out;
});

const settings: ConstructorParameters<typeof PageFlip>[1] = {
  width: 400,
  height: 300,
  size: 'fixed',
  usePortrait: flag('portrait'),
  showCover: flag('cover'),
  direction: flag('rtl') ? 'rtl' : 'ltr',
  flippingTime: Number(params.get('flippingTime') ?? 600),
  // Paper colour is a probe target: it is what must show through where a
  // transparent bitmap does not paint, and what a blank / failed leaf shows.
  pageBackground,
  // Shadows resample and would poison a flat-colour probe.
  drawShadow: flag('shadow'),
  respectReducedMotion: params.get('reducedMotion') !== '0',
};

// Book-level fit / inset when the engine exposes them (ADR Decision 4).
const settingsRecord = settings as Record<string, unknown>;
if (fit === 'contain' || fit === 'cover' || fit === 'fill') {
  settingsRecord['imageFit'] = fit;
}
if (inset !== undefined && Number.isFinite(inset)) {
  settingsRecord['imageInset'] = inset;
}

const book = new PageFlip(root, settings);

declare global {
  interface Window {
    flipbook: PageFlip;
    flipbookError: string | null;
    /** True when loadFromImages accepted ImagePageSource descriptors. */
    flipbookDescriptors: boolean;
    /** Captured imageError payloads for e2e (ADR Decision 2). */
    flipbookImageErrors: Array<{ page: number; src: string; attempt: number }>;
  }
}

window.flipbook = book;
window.flipbookError = null;
window.flipbookDescriptors = false;
window.flipbookImageErrors = [];

for (const name of ['flip', 'changeState', 'changeOrientation'] as const) {
  book.on(name, () => {
    document.body.dataset['state'] = book.getState();
    document.body.dataset['page'] = String(book.getCurrentPageIndex());
  });
}

// ADR Decision 2: imageError is the only signal for a failed leaf.
// Typed loosely until core exports the payload on FlipbookEventMap.
try {
  (
    book.on as (
      event: string,
      cb: (e: { data: { page: number; src: string; attempt: number } }) => void,
    ) => void
  )('imageError', (e) => {
    window.flipbookImageErrors.push(e.data);
    document.body.dataset['imageError'] = String(window.flipbookImageErrors.length);
  });
} catch {
  // Older engines reject unknown event names — Phase 0 still runs.
}

/**
 * Prefer the ADR descriptor list. If the engine still only accepts `string[]`
 * (pre-Phase 2), strip to URLs so the harness keeps working. Blank leaves have
 * no URL — those fixtures require Phase 2 and surface as a ready=unsupported
 * flag rather than a false green.
 */
function toLoadArg(): unknown {
  const hasBlank = descriptors.some((d) => d.blank === true);
  const needsDescriptor =
    hasBlank ||
    descriptors.some(
      (d) => d.fit !== undefined || d.inset !== undefined || d.background !== undefined,
    );

  // Try descriptors first when the fixture actually needs them.
  if (needsDescriptor || fit !== null || inset !== undefined) {
    return descriptors;
  }

  // Default identity pages: bare strings still compile against today's API.
  return descriptors.map((d) => d.src).filter((s): s is string => typeof s === 'string');
}

const loadArg = toLoadArg();

book
  .loadFromImages(loadArg as string[])
  .then(() => {
    // Heuristic: if we passed objects and nothing threw, descriptors landed.
    window.flipbookDescriptors = Array.isArray(loadArg) && typeof loadArg[0] === 'object';
    document.body.dataset['ready'] = '1';
    document.body.dataset['descriptors'] = window.flipbookDescriptors ? '1' : '0';
    document.body.dataset['page'] = String(book.getCurrentPageIndex());
    document.body.dataset['state'] = book.getState();
    const fitSetting = (book.getSettings() as unknown as Record<string, unknown>)['imageFit'];
    document.body.dataset['fit'] = typeof fitSetting === 'string' ? fitSetting : 'legacy-fill';
  })
  .catch((err: unknown) => {
    // Descriptor rejection (pre-Phase 2 engine) — retry with bare strings so
    // Phase 0 tests still run, and mark the Phase 2 surface unsupported.
    const message = err instanceof Error ? err.message : String(err);
    const wasDescriptors = Array.isArray(loadArg) && typeof loadArg[0] === 'object';
    if (wasDescriptors) {
      const urls = descriptors.map((d) => d.src).filter((s): s is string => typeof s === 'string');
      if (urls.length === 0) {
        window.flipbookError = message;
        document.body.dataset['ready'] = 'unsupported';
        document.body.dataset['descriptors'] = '0';
        return;
      }
      return book
        .loadFromImages(urls)
        .then(() => {
          window.flipbookDescriptors = false;
          document.body.dataset['ready'] = '1';
          document.body.dataset['descriptors'] = '0';
          document.body.dataset['page'] = String(book.getCurrentPageIndex());
          document.body.dataset['state'] = book.getState();
          document.body.dataset['fit'] = 'legacy-fill';
          document.body.dataset['phase2'] = 'pending';
        })
        .catch((err2: unknown) => {
          window.flipbookError = err2 instanceof Error ? err2.message : String(err2);
          document.body.dataset['ready'] = 'error';
        });
    }
    window.flipbookError = message;
    document.body.dataset['ready'] = 'error';
  });
