import { PageFlip } from '@gullabs/flipbook-core';

/**
 * Canvas-mode e2e harness.
 *
 * Deliberately separate from `main.ts`: this is not a showcase, it is a rig for
 * reading pixels off a canvas deterministically. The fixtures are generated by
 * `scripts/gen-canvas-fixtures.mjs`, so the exact colour at every probe point
 * is derivable from source rather than being a committed mystery.
 *
 * `data-ready` says the engine was constructed. It does NOT mean images are
 * decoded — `loadFromImages` resolves once the canvas chunk has loaded, not
 * once the book has painted. Tests must poll pixels, never trust this flag.
 */
const root = document.getElementById('book');
if (!(root instanceof HTMLElement)) {
  throw new Error('#book root element is required');
}

const params = new URLSearchParams(window.location.search);
const flag = (name: string): boolean => params.get(name) === '1';

if (flag('fractional')) document.body.dataset['fractional'] = '1';
if (flag('hidden')) document.body.dataset['hidden'] = '1';

const pageCount = Number(params.get('pages') ?? 6);
const sources: string[] =
  params.get('fixture') === 'transparent'
    ? ['/fixtures/canvas/transparent.png', '/fixtures/canvas/page-1.png']
    : Array.from({ length: pageCount }, (_, i) => `/fixtures/canvas/page-${String(i % 6)}.png`);

const book = new PageFlip(root, {
  width: 400,
  height: 300,
  size: 'fixed',
  usePortrait: flag('portrait'),
  showCover: flag('cover'),
  direction: flag('rtl') ? 'rtl' : 'ltr',
  flippingTime: Number(params.get('flippingTime') ?? 600),
  // Paper colour is a probe target: it is what must show through where a
  // transparent bitmap does not paint.
  pageBackground: params.get('pageBackground') ?? '#f4ecd8',
  // Shadows resample and would poison a flat-colour probe.
  drawShadow: flag('shadow'),
  respectReducedMotion: params.get('reducedMotion') !== '0',
});

declare global {
  interface Window {
    flipbook: PageFlip;
    flipbookError: string | null;
  }
}

window.flipbook = book;
window.flipbookError = null;

for (const name of ['flip', 'changeState', 'changeOrientation'] as const) {
  book.on(name, () => {
    document.body.dataset['state'] = book.getState();
    document.body.dataset['page'] = String(book.getCurrentPageIndex());
  });
}

book
  .loadFromImages(sources)
  .then(() => {
    document.body.dataset['ready'] = '1';
    document.body.dataset['page'] = String(book.getCurrentPageIndex());
    document.body.dataset['state'] = book.getState();
  })
  .catch((err: unknown) => {
    window.flipbookError = err instanceof Error ? err.message : String(err);
    document.body.dataset['ready'] = 'error';
  });
